Pass-Supported-Platform
cloudify-cosmo/wagon pull request #143
Opened 2022-01-27 15:54 UTC by ahmadiesa-abu

this PR address platform issue in case of new manylinux wheel naming convention [pep600 concatenate]

2022-01-27 15:56 UTC, EarthmanT submitted a review, later dismissed

2022-01-28 01:08 UTC, tehasdf requested changes
this wont work because in the simple case of platform = `manylinux_2_5_x86_64` (which is a pep600 alias for `manylinux1_x86_64`), the platform here ends up being `linux_2_5_x86_64`, which isn't valid (`linux_x86_64` is)

2022-01-28 01:08 UTC, tehasdf commented on wagon.py
> +            platform=platform.partition('_')[2]
```suggestion
            platform = platform.partition('_')[2]
```
huh we dont have flake8 in ci here, and apparently ci doesnt work anyway

2022-01-28 01:12 UTC, tehasdf commented
all in all the best idea is probably to just drop the 5.1-compat hack, because passing in the `--supported-platform` correctly means that plugins that need to be 5.1-compatible, can just be built with the override passed in

2022-01-28 06:56 UTC, ahmadiesa-abu commented
> this wont work because in the simple case of platform = `manylinux_2_5_x86_64` (which is a pep600 alias for `manylinux1_x86_64`), the platform here ends up being `linux_2_5_x86_64`, which isn't valid (`linux_x86_64` is)

I have added another snippet that handles these extreme cases

2022-01-28 06:57 UTC, ahmadiesa-abu commented
> all in all the best idea is probably to just drop the 5.1-compat hack, because passing in the `--supported-platform` correctly means that plugins that need to be 5.1-compatible, can just be built with the override passed in

I agree , that is why we fixed the create function to pass in `supported-platform` , but we also need to be able to handle it , if the user doesn't pass it also

2022-01-31 09:54 UTC, tehasdf approved these changes

2022-01-31 13:48 UTC, EarthmanT approved these changes

2022-01-31 13:49 UTC, merged